trigger:
- main

pool:
  name: Default

jobs:
- job:
  displayName: "Tf-Serving Image Build Push"
  
  steps:
  
  - task: Docker@0
    displayName: 'Build an image'
    inputs:
      azureSubscription: 'Azure subscription 1(e6d4c51e-0d82-4960-829a-196186580859)'
      azureContainerRegistry: '{"loginServer":"garbagenettrainer.azurecr.io", "id" : "/subscriptions/e6d4c51e-0d82-4960-829a-196186580859/resourceGroups/ELG5164-Garbagenet/providers/Microsoft.ContainerRegistry/registries/GarbagenetTrainer"}'
      imageName: 'garbagenet-tf-serving'
      includeLatestTag: true
      
  - task: Docker@0
    displayName: 'Push an image'
    inputs:
      azureSubscription: 'Azure subscription 1(e6d4c51e-0d82-4960-829a-196186580859)'
      azureContainerRegistry: '{"loginServer":"garbagenettrainer.azurecr.io", "id" : "/subscriptions/e6d4c51e-0d82-4960-829a-196186580859/resourceGroups/ELG5164-Garbagenet/providers/Microsoft.ContainerRegistry/registries/GarbagenetTrainer"}'
      action: 'Push an image'
      imageName: 'garbagenet-tf-serving'
      includeLatestTag: true
