apiVersion: apps/v1
kind: Deployment
metadata:
  name: "garbagenet-deployment"
spec:
  selector:
    matchLabels:
      app: "garbagenet"
  replicas: 3
  template:
    metadata:
      labels:
        app: "garbagenet"
    spec:
      imagePullSecrets:
        - name: acr-auth-secret
      containers:
        - name: "garbagenet"
          image: garbagenettrainer.azurecr.io/garbagenet-tf-serving:latest
          ports:
          - containerPort: 8500
          - containerPort: 8501
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "garbagenet-service"
  namespace: "default"
  labels:
    app: "garbagenet"
spec:
  ports:
  - name: "tensorflow-svc"
    protocol: "TCP"
    port: 8500
    targetPort: 8500
  - name: "tensorflow-rest"
    protocol: "TCP"
    port: 8501
    targetPort: 8501
  selector:
    app: "garbagenet"
  type: "LoadBalancer"
